
services:
  db:
    image: postgres:17.4
    container_name: tourwise-db
    build:
      context: ./src/db-docker
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - tourwise-db-data:/var/lib/postgresql/data
    networks:
      - tourwise-net

backend-service:
    build:
      context: ./src/backend-service
    container_name: tourwise-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - tourwise-net
    env_file:
      - ./src/backend-service/.env

  scrappers:
    build:
      context: ./src/scrappers
    container_name: tourwise-scrappers
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - tourwise-net
    env_file:
      - ./src/scrappers/.env

  frontend:
    build:
      context: ./src/frontend
    container_name: tourwise-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend-service
    networks:
      - tourwise-net

volumes:
  tourwise-db-data:

networks:
  tourwise-net:
    driver: bridge
