services:

  backend:
    image: ${BACKEND_IMAGE}
    container_name: tourwise-backend
    env_file:
      - ./backend/.env.prod
    ports:
      - "8080:8080"
    networks:
      - tourwise-network
    mem_limit: 1500m
    memswap_limit: 2000m
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"


  scraper:
    image: ${SCRAPER_IMAGE}
    container_name: tourwise-scraper
    ports:
      - "8081:8081"
    env_file:
      - ./scraper/.env.prod
    networks:
      - tourwise-network

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: tourwise-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - tourwise-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"


  watchtower:
    image: containrrr/watchtower
    container_name: tourwise-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true                # 自动删除旧镜像
      - WATCHTOWER_POLL_INTERVAL=300          # 每 300 秒（5 分钟）检查一次
      - WATCHTOWER_INCLUDE_RESTARTING=true    # 处理正在重启的容器
      - WATCHTOWER_LABEL_ENABLE=true          # 只更新带 label 的容器（可选，下面说明）
    restart: unless-stopped
    networks:
      - tourwise-network


networks:
  tourwise-network:

